# Generated by Django 3.1.7 on 2021-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wyjazd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=300)),
                ('data_wy', models.TimeField(default=False)),
                ('czas_do', models.TimeField(default=False)),
                ('czas_po', models.TimeField(default=False)),
                ('data_po', models.DateTimeField(default=False)),
                ('osoby', models.CharField(max_length=500)),
                ('samochod', models.CharField(blank=True, max_length=20)),
                ('j_sniadanie', models.IntegerField()),
                ('j_obiad', models.IntegerField()),
                ('j_kolacja', models.IntegerField()),
            ],
        ),
    ]
