# Generated by Django 3.1.7 on 2021-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyjazd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyjazd',
            name='czas_do',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wyjazd',
            name='czas_po',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
