# Generated by Django 3.1.7 on 2021-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyjazd', '0002_auto_20210304_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyjazd',
            name='data_wy',
            field=models.DateTimeField(default=False),
        ),
    ]
